language: ruby
rvm:
  - 2.0.0
before_script:
  - bundle exec rake compile
  - bundle exec rake serve > /dev/null 2>&1 &
  - export PID=$!
  - sleep 3
script:
  - bundle exec rake spec
after_failure:
  - bundle exec rake upload
after_script:
  - kill -2 $PID
  - sleep 3
